env:
  browser: true
  node: true
  es6: true

extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  linebreak-style:
    - off
  no-useless-escape:
    - off
  indent:
    - warn
    - 2
    - SwitchCase: 1
  no-unused-vars:
    - warn
  no-console:
    - warn
  no-cond-assign:
    - warn
